# https://github.com/mhausenblas/mkdocs-template?tab=readme-ov-file
# https://github.com/marketplace/actions/deploy-mkdocs

name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          # CUSTOM_DOMAIN: optionaldomain.com
          # GITHUB_DOMAIN: github.myenterprise.com
          # REQUIREMENTS: folder/requirements.txt
