# https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Multi-Platform

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04] # [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake catch2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
